### PR TITLE
Update CSS so that link color is $tc-dark-blue-110(#006dea)

### PR DESCRIPTION
**Pull request by kkartunov**

### CODE REVIEW

**Comment by kkartunov** [comment]
Aimed to fix https://github.com/topcoder-platform/community-app/issues/1648

**Comment by kkartunov** [comment]
@birdofpreyru ^^^

**Comment by birdofpreyru** [comment]
@kkartunov I have not actively participated in anything related to community-app in the last few weeks, thus it makes not much sense to request my review :) Also, this looks just a simple style correction, if we need it, ok :)

**Comment by kkartunov** [comment]
@birdofpreyru Sorry to bother you but I can't merge myself due to:
 > "The base branch restricts merging to authorized users."

and 

> You’re not authorized to merge this pull request.

You can elevate my access to repo to avoid such requests in the future. FOr now please just merge it. Thanks!

**Comment by birdofpreyru** [comment]
@kkartunov 
Ah, ok, I provided you push rights for _master_

**Pull request merged**
