### PR TITLE
MSFT-83

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for https://github.com/topcoder-platform/community-app/issues/2794

### CODE REVIEW

**Comment by sushilshinde** [comment]
@r0hit-gupta please PR to `qa-accessibility` branch

**Comment by r0hit-gupta** [comment]
@sushilshinde  done

**Comment by veshu** [comment]
@r0hit-gupta Sorry to bring, but please update the color code according palette guide, 

Also ensure that you are using color palette name instead of hex code directly. 

I will update the prize for ticket.

**Comment by r0hit-gupta** [comment]
@veshu done

**Pull request merged**
