### PR TITLE
MSFT-85

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for https://github.com/topcoder-platform/community-app/issues/2796

### CODE REVIEW

**Comment by sushilshinde** [comment]
@r0hit-gupta please PR to `qa-accessibility` branch

**Comment by r0hit-gupta** [comment]
@sushilshinde done

**Comment by veshu** [comment]
@r0hit-gupta Please use variable name `$tc-dark-blue-120` for this color 006ad7,

**Comment by r0hit-gupta** [comment]
@veshu done. Used `$tc-dark-blue-110` which represents `#006ad7` in the palette https://marvelapp.com/c7h2a6h/screen/59648056/handoff

**Comment by veshu** [comment]
@r0hit-gupta Please confirm, i don't think we need this PR, as tc-dark-blue is same as tc-dark-blue-110.

Once you confirm, close this PR and update your issue/PR related to this reference color palette Pr will fix this.

**Comment by r0hit-gupta** [comment]
@veshu no `$tc-dark-blue` is not same as `$tc-dark-blue-110`. https://github.com/topcoder-platform/topcoder-react-ui-kit/blob/587b17f3641162ace3af2affb930f4a02efb3eee/src/styles/_mixins/variables.scss#L122
We still require this PR.

**Comment by veshu** [comment]
Thanks, thats correct palette definition.

**Pull request merged**
