### PR TITLE
Fixes Issue #2881 - added new colors

### PR DESCRIPTION
**Pull request by romitgit**

### CODE REVIEW

**Comment by veshu** [comment]
@romitgit target Branch is wrong.

Also the color code you are using are not correct for name.

**Comment by veshu** [comment]
@romitgit please check this palette to define the color https://marvelapp.com/c7h2a6h/screen/59648056/handoff

**Comment by romitgit** [comment]
@veshu made the changes. Please review.

**Comment by veshu** [comment]
@romitgit Please check lint and test before submitting your PR.

**Comment by romitgit** [comment]
@veshu done now.

**Comment by veshu** [comment]
@codeMinter Please take care of this, all this color palette is fixed by another PR. 

Once you verified corresponding issue, you can close this issue safely.

**Comment by codeMinter** [comment]
@romitgit we don't need this PR now since you are using one of the defined color palette in your changes. So closing this.

**Pull request closed without merging**
