### PR TITLE
issue 2907 fix

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by sushilshinde** [comment]
@rashmi73 please PR to `qa-accessibility` branch

**Comment by rashmi73** [comment]
@sushilshinde PR has been raised for qa-acessibility as well .
https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/13

**Comment by codeMinter** [comment]
@sushilshinde let's merge this so we can test 2907 on community-app

**Comment by sushilshinde** [comment]
@codeMinter @rashmi73 lint is failing because of code is in capital 

Please npm lint and please PR again

**Pull request merged**
