### PR TITLE
issue 2871 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by sushilshinde** [comment]
@PrakashDurlabhji please PR to `qa-accessibility` branch

**Comment by veshu** [comment]
@PrakashDurlabhji Please change the target branch.

Also, please double check that you are not altering the theme of the tags. please check here https://marvelapp.com/c7h2a6h/screen/59648056/handoff for color palette.

**Comment by PrakashDurlabhji** [comment]
@veshu yes i am not updating the theme color at all. it is same from color pallete.
branch changed

**Comment by veshu** [comment]
You are totally breaking the theme here, you have changed the green button to blue button. white text to gray text. I am rejecting this PR which is not acceptable. 

Also please ask if you need color help, don't make review slower by wrong fixes.

**Comment by PrakashDurlabhji** [comment]
@veshu sorry for that if wrong, but it will just change it when hovered. because that needs to be matched correct? similar to others?

**Comment by veshu** [comment]
@PrakashDurlabhji The development tags code, first2Finish are green , design and design f2f are blue, and marathon have orange color, they should be same even for highlight 

Check my temp fixes https://monosnap.com/file/GvuXzytRFfu1CL8JyCD4z2aTtp5DNZ , 

When button or tag background color is .button {
  background-color: $tc-light-blue; then when hover /active make the background-color to $tc-light-blue-110

similar for green the normal background color will be $tc-green now you need to change $tc-green-110 for hover/active case. 

make sure to do on all three files https://github.com/topcoder-platform/topcoder-react-ui-kit/tree/qa-accessibility/src/shared/components/tags

**Pull request closed without merging**
